### ISSUE TITLE
提示如下错误信息

### ISSUE THREAD

**Issue by callmeYe** [golmic/mafengwo-spider#3]
D:\mafengwo-spider-master>node spider.js
D:\mafengwo-spider-master\spider.js:92
            articlesUrl[i] = res[i * 3].substr(3, 7);
                                ^
TypeError: Cannot read property '0' of null
    at Request._callback (D:\mafengwo-spider-master\spider.js:92:33)
    at Request.self.callback (D:\mafengwo-spider-master\node_modules\request\req
uest.js:188:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (D:\mafengwo-spider-master\node_modules\request\reque
st.js:1171:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (D:\mafengwo-spider-master\node_modules\reque
st\request.js:1091:12)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by golmic** [comment]
@callmeYe 可能因为蚂蜂窝界面改版导致代码无法使用，我这两天手边没电脑不能帮你解决，如果着急的话你可以留下你的联系方式我跟你沟通，如果不着急的话我大概会在下周末回复你关于这个问题的解决方案。谢谢对项目的关注！

**Comment by golmic** [comment]
因为蚂蜂窝页面改版，本项目不再维护，如果还有需求的话单独联系我吧，联系方式简历中有写到。
